using Microsoft.AspNetCore.Http;
using System;
using System.Threading.Tasks;

namespace BackendAPI.Helpers
{    /// <summary>
     /// Helper for Google Cloud Storage. Provides methods to upload and delete files from the aplication's storage bucket. May be modified for other similar solutions such as AWS S3 or Azure Blob.
     /// </summary>
    public interface IGoogleCloudStorageHelper
    {
        /// <summary>
        /// Uploads a File to the Storage Bucket alongside with its Object/File Name. By default an Object/File name is automatically generated by each Repository's method according to its use case
        /// that makes use of this function passing it to this function and is stored in the database alongside the corresponding storage bucket access URL.
        /// If the file is an image or a video it should be validated beforehand with the mehods in the File Helper class.
        /// </summary>
        /// <param name="File">Form File to upload</param>
        /// <param name="DestinationFileName">Object/File name of the file in the storage bucket</param>
        /// <returns></returns>

        Task<String> Upload(IFormFile File, string DestinationFileName);
        /// <summary>
        /// Deletes a File From the Storage Bucket by its Object Name.
        /// </summary>
        /// <param name="DestinationFileName">Object/File name of the file in the storage bucket</param>
        /// <returns></returns>
        Task Delete(string DestinationFileName);
    }
}
