namespace BackendAPI.Entities.Enums
{
    public enum ErrorType
    {
        //ADICIONAR SEMPRE NOVAS ENUMERAÇÕES NO FIM
        AUTHENTICATION_EMAIL_EXISTS = 0,
        AUTHENTICATION_USERNAME_EXISTS = 1,
        AUTHENTICATION_WRONG_PASSWORD = 2,
        AUTHENTICATION_ACCOUNT_NOT_CONFIRMED = 3,
        AUTHENTICATION_INVALID_PASSWORD = 4,
        AUTHENTICATION_INVALID_USER = 5,
        AUTHENTICATION_DELETED_ACCOUNT = 6,
        AUTHENTICATION_WRONG_PASSWORD_RESET = 7,
        AUTHENTICATION_WRONG_EMAIL_CONFIRMATION = 8,
        AUTHENTICATION_EMAIL_ALREADY_CONFIRMED = 9,
        AUTHENTICATION_ACCOUNT_CREATION_ERROR = 10,


        RANKING_DEFAULT_DELETE = 11,
        RANKING_EXISTS = 12,
        RANKING_INVALID_NUMBER_MINIMUM_KILOMETERS = 53,

        ACTIVITY_TYPE_NOT_DEFINED = 13,
        ACTIVITY_TRANSPORT_TYPE_NOT_DEFINED = 14,
        ACTIVITY_NOT_IN_TRIP_RANGE = 15,
        ACTIVITY_NOT_SAME_DAY = 16,
        ACTIVITY_MISSING_TRANSPORT = 17,
        ACTIVITY_REPEATED = 18,
        ACTIVITY_OVERLAP = 19,
        ACTIVITY_REMOVE_TRANSPORT = 20,
        ACTIVITY_REMOVE_NOT_LAST = 21,
        ACTIVITY_CHANGE_TYPE = 22,
        ACTIVITY_PLACE_ID_NONEXIST = 23,
        ACTIVITY_SEARCH_TRANSPORT_NO_DEPARTURE_AND_ARRIVAL_TIME = 51,

        TRIP_COMPLETED = 24,
        TRIP_INVITE_INVALID = 25,
        TRIP_USER_ALREADY_PRESENT = 26,
        TRIP_USER_ALREADY_INVITED = 27,
        TRIP_USER_NOT_PRESENT_GROUP = 28,
        TRIP_DATE_INVALID = 29,
        TRIP_DATE_EXISTING_ACTIVITIES = 30,
        TRIP_USER_NOT_PRESENT = 31,

        GROUP_INVITE_INVALID = 32,
        GROUP_USER_ALREADY_PRESENT = 33,
        GROUP_USER_ALREADY_INVITED = 34,
        GROUP_USER_NOT_PRESENT = 35,
        GROUP_LAST_MANAGER_LEAVE = 36,
        GROUP_ROLE_INVALID = 37,
        GROUP_MANAGER_MANAGE_ITSELF = 38,
        GROUP_USER_ALREADY_BANNED = 46,
        GROUP_USER_NOT_BANNED = 47,
        GROUP_USER_JOIN_BANNED = 48,
        GROUP_BAN_DATE_INVALID = 50,

        POST_DATE_INVALID = 39,
        POST_USER_NOT_IN_TRIP = 52,

        INVALID_COUNTRY_CODE = 40,
        EMAIL_ERROR = 41,
        MEDIA_ERROR = 42,
        OTHER = 43,

        USER_ALREADY_FOLLOWING = 44,
        USER_NOT_FOLLOWING = 45,
        USER_NOT_FOLLOW_SELF = 49
    }
}
